### ISSUE TITLE
Finish this piece of shit...checklist

### ISSUE THREAD

**Issue by Michael080** [Michael080/Scrimba_Front-End-Path#42]
You've been pixelimifying this God forsaken site for way more than too damn much. FINISH IT :{
- [x] QC ALL links
- [x] Consolidate any rules that can be
- [x] Remove ALL temp/unused classes etc,.
- [x] Realize how wrong your solution is and save notes in dir
- [x] Figure out alt-text for background images
- [x] Fix off-center navlinks
- [x] Make <p>-text on about-me-aside blue
